apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: master
        image: worker:protobuf
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 5001
---
